---
title: "Introduction to R {packages}"
author: "Leigh Alexander"
date: '`r Sys.Date()`'
output: 
  html_document:
    code_folding: hide
    df_print: kable
    theme: flatly
    toc: yes
    toc_float: yes
  number_sections: true
editor_options: 
  chunk_output_type: console
---
    
```{r setup, include=FALSE}
options(knitr.table.format = "html", width=600)
knitr::opts_chunk$set(message=FALSE, warning=FALSE, cache=FALSE, error = TRUE)
```


# Why would I want to make a package?
*"Anything that can by automated, should be automated."*  
- Hadley Wickham & Jenny Bryan   


* Sharing code across teams or with collaborators
* Tools that enable reproducibility and testing
* Reusing my functions
* My own analysis project

<br><br><br><br>

## Sharing code

* Streamlines and standardizes code across teams/labs
* Reduces duplicative efforts
* Highly portable
* Easier to specify relative paths
* "It works on my machine"

<br><br>

## Tools that enable reproducibility and testing

*"Packages are the fundamental units of reproducible R code."*  
- HW & JB

* Unit tests!
* Dependency management
* R version/package version management

<br><br>

## Reusing my own functions

### Rule of threes

* If you copy and paste code 3 times, make it a function
* If you re-use a function 3 times, make it a package

<br><br>

## Analysis project

* Put an end to source("path/to/my/file")!
* Use wrapper functions to create same plots across scripts/RMarkdown files
    + multiple chapters in one document
    + move from html, to Word, to Powerpoint
   
<br><br><br><br>

# Basic Components of an R package
## Folder Structure

* R 
* [DESCRIPTION](#desc-link) 
* [NAMESPACE](#ns-link)
* tests
* [data](#data-link)
* inst
  
<br><br>

### DESCRIPTION {#desc-link}
* All the general info/meta data about your package
* Required for packages, how RStudio and devtools "know" your folder is a pkg
* Specially formatted so that documentation is generated automatically  
* Dependencies
    + Imports
        - a pkg is *required* for your pkg to work
        - is installed along with your pkg
        - but is not *loaded* when your pkg is
    + Suggests

<br><br>

### NAMESPACE {#ns-link}

*"To play nicely with others, your package needs to define what functions it makes available to other packages and what functions it requires from other packages"*  
- HW & JB  

* Manages what you import and export
* Makes your package "self-contained"
* relates to searchPaths

<br><br>

### Data {#data-link}

* /data
    + for .Rdata files
    + generally, cleaned up versions of data
    + takes advantage of lazy loading
* /data-raw
    + your raw data + the .R file with the code you used to clean it up
    + takes advantage of package file path

#### inst

* Whatever you want, pretty much

<br><br><br><br>

# Parking Lot

* Don't make library(), source(), or setwd() calls in your functions
* R packages use the top level of your package folder as your working directory
    + So you don't want to nest your package under an Rproj, other package, or git repo
* Avoid use of . in your functions names
* Unit tests
    + saves future you from debugging/points to where to debug
    + forces you to think more about code design
    + code is more robust

<br><br><br><br>

# Resources

[r-pkg-book](https://r-pkgs.org/) 
[usethis](https://usethis.r-lib.org/)  
[usethis-workflow](https://www.hvitfeldt.me/blog/usethis-workflow-for-package-development/)  
[tidyverse-dev](https://usethis.r-lib.org/reference/tidyverse.html)  
[examples-on-github-forcats](https://github.com/tidyverse/forcats)  

## Writing functions
[r-4-data-science](https://r4ds.had.co.nz/functions.html)  
[advanced-r](https://adv-r.hadley.nz/functions.html)  

# Things to Demo
* See R script
* Folder package structure
* load_all(), document(), check(), test()
* Example of roxygen documentation 
* Install package and use ?
